packages:
  - 'apps/*'
allowBuilds:
  '@prisma/engines': true
  argon2: true
  better-sqlite3: true
  cpu-features: true
  dugite: false
  electron: false
  electron-winstaller: false
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
