package main

/*
Changes made:
- Replaced the Python one-click deployer with a Go CLI so the public installer
  can ship as a single compiled binary with no Python, pip, or runtime package
  setup on user laptops.
- Kept install.sh as the curl|bash entrypoint; it detects OS/arch, installs
  the matching archectl binary locally, and runs the requested lifecycle command.
- Added install, update, and destroy commands. Install/update accept a version
  tag and use it for both GHCR web and workspace images.
- Preserved the narrow-path deployment behavior: DigitalOcean only,
  autogenerated secrets, autogenerated nip.io hostname, Docker,
  PostgreSQL, Traefik, docker-socket-proxy, persistent KB/user mounts, public
  health polling, local credential file, and inline remote bootstrap logs.

Language choice: Go, because this installer is meant to run on arbitrary user
laptops and a static-ish single binary is more reliable than bootstrapping a
Python runtime plus terminal UI dependencies.
*/

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"math"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/charmbracelet/lipgloss"
	"golang.org/x/term"
)

const (
	appName                     = "arche"
	appImageRepo                = "ghcr.io/peaberry-studio/arche/web"
	workspaceImageRepo          = "ghcr.io/peaberry-studio/arche/workspace"
	defaultVersion              = "latest"
	appPort                     = 3000
	dbName                      = "arche"
	defaultDropletSize          = "s-2vcpu-4gb"
	defaultDropletRegion        = "nyc1"
	dropletImage                = "ubuntu-24-04-x64"
	doAPIBase                   = "https://api.digitalocean.com/v2"
	envPlaceholderDomain        = "__ARCHE_DOMAIN__"
	envPlaceholderPublicBaseURL = "__ARCHE_PUBLIC_BASE_URL__"
	defaultHealthWait           = 12 * time.Minute
)

type input struct {
	token   string
	email   string
	size    string
	region  string
	version string
}

type secretsData struct {
	postgresPassword          string
	sessionPepper             string
	encryptionKey             string
	internalToken             string
	gatewayTokenSecret        string
	connectorOAuthStateSecret string
	adminPassword             string
	rootPassword              string
}

type artifacts struct {
	DropletID       int    `json:"droplet_id"`
	FirewallID      string `json:"firewall_id"`
	DropletName     string `json:"droplet_name"`
	IPAddress       string `json:"ip_address"`
	Domain          string `json:"domain"`
	PublicURL       string `json:"public_url"`
	AdminEmail      string `json:"admin_email"`
	CredentialsFile string `json:"credentials_file"`
	JSONFile        string `json:"json_file"`
}

type healthResult struct {
	Ready          bool
	ElapsedSeconds int
	LastStatus     string
}

type cliArgs struct {
	command        string
	token          string
	email          string
	size           string
	region         string
	version        string
	statePath      string
	ipAddress      string
	sshPassword    string
	publicURL      string
	dropletID      int
	firewallID     string
	skipHealthWait bool
	validateOnly   bool
	verbose        bool
	yes            bool
	help           bool
}

type stateInput struct {
	Email         string `json:"email"`
	DropletSize   string `json:"droplet_size"`
	DropletRegion string `json:"droplet_region"`
}

type stateSecrets struct {
	PostgresPassword          string `json:"postgres_password"`
	SessionPepper             string `json:"session_pepper"`
	EncryptionKey             string `json:"encryption_key"`
	InternalToken             string `json:"internal_token"`
	GatewayTokenSecret        string `json:"gateway_token_secret"`
	ConnectorOAuthStateSecret string `json:"connector_oauth_state_secret"`
	AdminPassword             string `json:"admin_password"`
	RootPassword              string `json:"root_password"`
}

type deploymentState struct {
	AppName        string       `json:"app_name"`
	Version        string       `json:"version"`
	AppImage       string       `json:"app_image"`
	WorkspaceImage string       `json:"workspace_image"`
	DBName         string       `json:"db_name"`
	Input          stateInput   `json:"input"`
	Deployment     artifacts    `json:"deployment"`
	Secrets        stateSecrets `json:"secrets"`
	UpdatedAt      string       `json:"updated_at"`
}

type legacyArtifacts struct {
	DropletID       int    `json:"DropletID"`
	FirewallID      string `json:"FirewallID"`
	DropletName     string `json:"DropletName"`
	IPAddress       string `json:"IPAddress"`
	Domain          string `json:"Domain"`
	PublicURL       string `json:"PublicURL"`
	AdminEmail      string `json:"AdminEmail"`
	CredentialsFile string `json:"CredentialsFile"`
	JSONFile        string `json:"JSONFile"`
}

type ui struct {
	mu             sync.Mutex
	step           int
	width          int
	interactive    bool
	progressActive bool
	progressWidth  int
	verbose        bool
	styles         uiStyles
}

type uiStyles struct {
	title     lipgloss.Style
	subtitle  lipgloss.Style
	panel     lipgloss.Style
	panelWarn lipgloss.Style
	panelOK   lipgloss.Style
	muted     lipgloss.Style
	cyan      lipgloss.Style
	green     lipgloss.Style
	yellow    lipgloss.Style
	bold      lipgloss.Style
}

func newUI() *ui {
	width := 92
	if terminalWidth, _, err := term.GetSize(int(os.Stdout.Fd())); err == nil {
		width = minInt(maxInt(72, terminalWidth-4), 108)
	}
	return &ui{
		width:       width,
		interactive: term.IsTerminal(int(os.Stdout.Fd())),
		styles: uiStyles{
			title:     lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("#F5F5F0")),
			subtitle:  lipgloss.NewStyle().Foreground(lipgloss.Color("#6EE7D8")),
			panel:     lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(lipgloss.Color("#6EE7D8")).Padding(1, 2).Width(width),
			panelWarn: lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(lipgloss.Color("#EAB308")).Padding(1, 2).Width(width),
			panelOK:   lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(lipgloss.Color("#22C55E")).Padding(1, 2).Width(width),
			muted:     lipgloss.NewStyle().Foreground(lipgloss.Color("#737373")),
			cyan:      lipgloss.NewStyle().Foreground(lipgloss.Color("#6EE7D8")),
			green:     lipgloss.NewStyle().Foreground(lipgloss.Color("#22C55E")),
			yellow:    lipgloss.NewStyle().Foreground(lipgloss.Color("#EAB308")),
			bold:      lipgloss.NewStyle().Bold(true),
		},
	}
}

func (u *ui) banner(title, subtitle string) {
	u.print(u.styles.panel.Render(lipgloss.JoinVertical(lipgloss.Left, u.styles.title.Render(title), u.styles.subtitle.Render(subtitle))))
}

func (u *ui) stage(title string) time.Time {
	u.step++
	u.log("STEP", u.styles.cyan, fmt.Sprintf("%02d  %s", u.step, u.styles.bold.Render(title)))
	return time.Now()
}

func (u *ui) info(message string) {
	u.log("INFO", u.styles.cyan, message)
}

func (u *ui) wait(message string) {
	u.log("WAIT", u.styles.cyan, message)
}

func (u *ui) ok(message string, started time.Time) {
	u.log("OK", u.styles.green, withDuration(message, started))
}

func (u *ui) warn(message string, started ...time.Time) {
	text := message
	if len(started) > 0 {
		text = withDuration(message, started[0])
	}
	u.log("WARN", u.styles.yellow, text)
}

func (u *ui) command(label, command string) {
	u.log("CMD", u.styles.muted, u.styles.bold.Render(label+": ")+u.styles.muted.Render(command))
}

func (u *ui) remote(message string) {
	if !u.verbose {
		return
	}
	u.log("REMOTE", u.styles.muted, u.styles.muted.Render(message))
}

func (u *ui) panel(title string, rows [][2]string, tone string) {
	u.mu.Lock()
	defer u.mu.Unlock()
	u.finishProgressLocked()

	style := u.styles.cyan.Bold(true)
	if tone == "success" {
		style = u.styles.green.Bold(true)
	}
	if tone == "warn" {
		style = u.styles.yellow.Bold(true)
	}
	maxKey := 0
	for _, row := range rows {
		maxKey = maxInt(maxKey, len(row[0]))
	}
	fmt.Println(style.Render(title))
	for _, row := range rows {
		key := u.styles.muted.Render(row[0] + strings.Repeat(" ", maxKey-len(row[0])))
		fmt.Println("  " + key + "  " + row[1])
	}
}

func (u *ui) progress(label string, current, total time.Duration, details string) string {
	ratio := 0.0
	if total > 0 {
		ratio = math.Max(0, math.Min(1, float64(current)/float64(total)))
	}
	width := 22
	filled := int(math.Round(ratio * float64(width)))
	bar := u.styles.cyan.Render(strings.Repeat("━", filled)) + u.styles.muted.Render(strings.Repeat("━", width-filled))
	return fmt.Sprintf("%s  %s  %3d%%  %s", u.styles.cyan.Bold(true).Render(label), bar, int(ratio*100), details)
}

func (u *ui) log(label string, style lipgloss.Style, message string) {
	timestamp := u.styles.muted.Render(time.Now().Format("15:04:05"))
	u.print(timestamp + " " + style.Render(label) + " " + message)
}

func (u *ui) print(lines ...string) {
	u.mu.Lock()
	defer u.mu.Unlock()
	u.finishProgressLocked()
	for _, line := range lines {
		fmt.Println(line)
	}
}

func (u *ui) progressWait(label string, current, total time.Duration, details string) {
	line := u.styles.muted.Render(time.Now().Format("15:04:05")) + " " + u.styles.cyan.Render("WAIT") + " " + u.progress(label, current, total, details)
	u.mu.Lock()
	defer u.mu.Unlock()
	if !u.interactive {
		fmt.Println(line)
		return
	}
	padding := ""
	plainWidth := lipgloss.Width(line)
	if u.progressWidth > plainWidth {
		padding = strings.Repeat(" ", u.progressWidth-plainWidth)
	}
	fmt.Print("\r" + line + padding)
	u.progressWidth = plainWidth
	u.progressActive = true
}

func (u *ui) progressDone(label string, total time.Duration, details string) {
	u.progressWait(label, total, total, details)
	u.mu.Lock()
	defer u.mu.Unlock()
	u.finishProgressLocked()
}

func (u *ui) finishProgressLocked() {
	if !u.progressActive {
		return
	}
	fmt.Println()
	u.progressActive = false
	u.progressWidth = 0
}

type doClient struct {
	token string
	http  *http.Client
}

func main() {
	ui := newUI()
	ctx, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stopSignals()

	code := run(ctx, ui)
	if code != 0 {
		os.Exit(code)
	}
}

func run(ctx context.Context, ui *ui) int {
	args, err := parseArgs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		printUsage(os.Stderr)
		return 1
	}
	if args.help {
		printUsage(os.Stdout)
		return 0
	}
	ui.verbose = args.verbose

	if err := validateVersion(args.version); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	if err := validateTemplates(args.version); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	if args.validateOnly {
		ui.ok("Template validation passed.", time.Time{})
		return 0
	}

	switch args.command {
	case "install":
		return runInstall(ctx, ui, args)
	case "update":
		return runUpdate(ctx, ui, args)
	case "destroy":
		return runDestroy(ctx, ui, args)
	default:
		fmt.Fprintln(os.Stderr, "Error: unsupported command "+args.command)
		printUsage(os.Stderr)
		return 1
	}
}

func runInstall(ctx context.Context, ui *ui, args cliArgs) int {
	var streamer *remoteStreamer
	defer func() {
		if streamer != nil {
			streamer.stop()
			if streamer.lastError != "" && !streamer.bootComplete() {
				ui.warn("Inline remote log stream ended early: " + streamer.lastError)
			}
		}
	}()

	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			ui.warn("Cancelled by user.")
			if streamer != nil {
				streamer.stop()
			}
			os.Exit(130)
		case <-done:
		}
	}()

	inputData, err := collectInput(args, ui)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}

	started := ui.stage("Generating secrets and first-boot payload")
	secrets := generateSecrets()
	envTemplate := renderEnvTemplate(inputData, secrets)
	composeContent := renderCompose()
	bootstrapScript := renderBootstrapScript()
	cloudInit := renderCloudInit(secrets, envTemplate, composeContent, bootstrapScript)
	ui.ok("Generated runtime secrets, cloud-init, .env template, and docker-compose.yml", started)

	client := &doClient{token: inputData.token, http: &http.Client{Timeout: 30 * time.Second}}
	started = ui.stage("Validating DigitalOcean API token")
	if err := client.validateToken(ctx); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("DigitalOcean API token accepted", started)

	started = ui.stage("Creating Droplet")
	dropletID, dropletName, err := createDroplet(ctx, client, inputData, cloudInit)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok(fmt.Sprintf("Created Droplet %s (id %d)", dropletName, dropletID), started)

	started = ui.stage("Waiting for the Droplet to become active")
	ipAddress, err := waitForDropletIP(ctx, client, dropletID, ui)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("Droplet is active with public IPv4 "+ipAddress, started)

	started = ui.stage("Attaching firewall")
	firewallID, err := createFirewall(ctx, client, dropletID, dropletName)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("Attached firewall "+firewallID+" with ports 22, 80, and 443 open", started)

	domain := buildDomainFromIP(ipAddress)
	publicURL := "https://" + domain
	started = ui.stage("Writing local deployment record")
	textFile, jsonFile, err := allocateLocalPaths()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	result := artifacts{
		DropletID:       dropletID,
		FirewallID:      firewallID,
		DropletName:     dropletName,
		IPAddress:       ipAddress,
		Domain:          domain,
		PublicURL:       publicURL,
		AdminEmail:      inputData.email,
		CredentialsFile: textFile,
		JSONFile:        jsonFile,
	}
	if err := writeLocalFiles(inputData, secrets, result); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("Saved deployment record to "+textFile, started)
	ui.info("Public URL: " + publicURL)
	if args.verbose {
		ui.command("Bootstrap logs", fmt.Sprintf("ssh root@%s 'tail -f /var/log/%s-bootstrap.log'", ipAddress, appName))
		ui.command("Compose logs", fmt.Sprintf("ssh root@%s 'cd /opt/%s && docker compose logs -f web'", ipAddress, appName))
	}

	if args.verbose {
		started = ui.stage("Opening the live remote bootstrap log")
		if waitForSSHPort(ctx, ipAddress, ui) {
			streamer = newRemoteStreamer(ui, ipAddress, secrets.rootPassword)
			if streamer.available() {
				if err := streamer.start(ctx); err != nil {
					ui.warn("Could not start inline remote log stream: "+err.Error(), started)
				} else if streamer.waitUntilAttached(15 * time.Second) {
					ui.ok("Streaming /var/log/arche-bootstrap.log inline", started)
				} else {
					ui.warn("SSH is reachable, but the live log stream has not attached yet. Health polling will continue.", started)
				}
			} else {
				ui.warn("Local ssh client not found. Falling back to manual log commands.", started)
			}
		} else {
			ui.warn("SSH did not open in time for the inline log stream. Falling back to manual log commands.", started)
		}
	}

	var health *healthResult
	if args.skipHealthWait {
		ui.warn("Skipping public health wait by request.")
	} else {
		started = ui.stage("Waiting for first boot, TLS, and the public health check")
		ui.info("This can take a few minutes while the server installs Docker, pulls images, and requests certificates.")
		result, err := waitForPublicHealth(ctx, publicURL, ui, defaultHealthWait)
		health = &result
		if err != nil {
			ui.warn(err.Error(), started)
		} else if result.Ready {
			ui.ok("Public health check passed for "+publicURL, started)
		}
	}

	printSummary(ui, result, health)
	return 0
}

func parseArgs(argv []string) (cliArgs, error) {
	args := cliArgs{command: "install", size: defaultDropletSize, region: defaultDropletRegion, version: defaultVersion}
	for len(argv) > 0 {
		if argv[0] == "-vv" || argv[0] == "--verbose" {
			args.verbose = true
			argv = argv[1:]
			continue
		}
		break
	}
	if len(argv) > 0 {
		switch argv[0] {
		case "install", "update", "destroy":
			args.command = argv[0]
			argv = argv[1:]
		case "help", "--help", "-h":
			args.help = true
			return args, nil
		default:
			if !strings.HasPrefix(argv[0], "-") {
				return args, fmt.Errorf("unknown command %q", argv[0])
			}
		}
	}

	flags := flag.NewFlagSet(args.command, flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	flags.BoolVar(&args.help, "help", false, "Show help")
	flags.BoolVar(&args.help, "h", false, "Show help")
	flags.BoolVar(&args.validateOnly, "validate-only", false, "Render and validate generated templates, then exit")
	flags.BoolVar(&args.verbose, "vv", args.verbose, "Show SSH/bootstrap logs")
	flags.BoolVar(&args.verbose, "verbose", args.verbose, "Show SSH/bootstrap logs")
	flags.StringVar(&args.version, "version", defaultVersion, "Arche image version tag, for example v1.2.3 or latest")

	switch args.command {
	case "install":
		flags.StringVar(&args.token, "token", "", "DigitalOcean API token")
		flags.StringVar(&args.email, "email", "", "Email for the Arche admin account and Let's Encrypt")
		flags.StringVar(&args.size, "size", defaultDropletSize, "Droplet size slug")
		flags.StringVar(&args.region, "region", defaultDropletRegion, "Droplet region slug")
		flags.BoolVar(&args.skipHealthWait, "skip-health-wait", false, "Do not wait for the public URL to answer")
	case "update":
		flags.StringVar(&args.token, "token", "", "DigitalOcean API token")
		flags.StringVar(&args.statePath, "state", "", "Path to deployment state JSON")
		flags.StringVar(&args.ipAddress, "ip", "", "Server IPv4 address when no state file is available")
		flags.StringVar(&args.sshPassword, "ssh-password", "", "Root SSH password when no state file is available")
		flags.StringVar(&args.publicURL, "url", "", "Public app URL when no state file is available")
		flags.BoolVar(&args.skipHealthWait, "skip-health-wait", false, "Do not wait for the public URL to answer after update")
	case "destroy":
		flags.StringVar(&args.token, "token", "", "DigitalOcean API token")
		flags.StringVar(&args.statePath, "state", "", "Path to deployment state JSON")
		flags.IntVar(&args.dropletID, "droplet-id", 0, "DigitalOcean Droplet id when no state file is available")
		flags.StringVar(&args.firewallID, "firewall-id", "", "DigitalOcean firewall id when no state file is available")
		flags.BoolVar(&args.yes, "yes", false, "Destroy without interactive confirmation")
	default:
		return args, fmt.Errorf("unknown command %q", args.command)
	}

	if err := flags.Parse(argv); err != nil {
		return args, err
	}
	if flags.NArg() > 0 {
		return args, fmt.Errorf("unexpected argument %q", flags.Arg(0))
	}
	if args.command == "update" && args.version == defaultVersion {
		return args, errors.New("update requires --version vX.X.X")
	}
	return args, nil
}

func printUsage(w io.Writer) {
	fmt.Fprintln(w, `Usage:
  archectl install [--token TOKEN] --email EMAIL [--version vX.X.X] [-vv]
  archectl update --token TOKEN --version vX.X.X [--state PATH] [-vv]
  archectl destroy --token TOKEN [--state PATH] [--yes]

Recovery without a state file:
  archectl update --token TOKEN --version vX.X.X --ip IP --ssh-password PASSWORD [--url URL]
  archectl destroy --token TOKEN --droplet-id ID [--firewall-id ID] --yes

If no command is provided, archectl defaults to install for curl|bash compatibility.
State defaults to ~/.arche/deployments/current.json.
Use -vv or --verbose to show SSH/bootstrap logs.`)
}

func collectInput(args cliArgs, ui *ui) (input, error) {
	reader := bufio.NewReader(os.Stdin)
	token, err := collectDOToken(args.token)
	if err != nil {
		return input{}, err
	}

	email := strings.TrimSpace(args.email)
	if email == "" {
		email = strings.TrimSpace(os.Getenv("ARCHE_INSTALL_EMAIL"))
	}
	if email == "" {
		fmt.Print("Email for the Arche admin account and Let's Encrypt: ")
		raw, err := reader.ReadString('\n')
		if err != nil {
			return input{}, fmt.Errorf("read email: %w", err)
		}
		email = strings.TrimSpace(raw)
	}

	if token == "" {
		return input{}, errors.New("DigitalOcean API token is required")
	}
	emailPattern := regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
	if !emailPattern.MatchString(email) {
		return input{}, errors.New("enter a valid email address")
	}

	ui.panel("Deployment plan", [][2]string{
		{"Droplet image", dropletImage},
		{"Droplet size", args.size},
		{"Droplet region", args.region},
		{"Version", args.version},
		{"Web image", appImageForVersion(args.version)},
		{"Workspace image", workspaceImageForVersion(args.version)},
		{"Public URL", "https://arche-<droplet-ip>.nip.io"},
	}, "info")
	fmt.Print("Continue and create the Droplet? (Y/n): ")
	answer, err := reader.ReadString('\n')
	if err != nil {
		return input{}, fmt.Errorf("read confirmation: %w", err)
	}
	answer = strings.ToLower(strings.TrimSpace(answer))
	if answer != "" && answer != "y" && answer != "yes" {
		return input{}, errors.New("deployment cancelled")
	}

	return input{token: token, email: email, size: args.size, region: args.region, version: args.version}, nil
}

func generateSecrets() secretsData {
	return secretsData{
		postgresPassword:          randPassword(28),
		sessionPepper:             randB64(32),
		encryptionKey:             randB64(32),
		internalToken:             randB64(32),
		gatewayTokenSecret:        randB64(32),
		connectorOAuthStateSecret: randB64(32),
		adminPassword:             randPassword(20),
		rootPassword:              randPassword(24),
	}
}

func randB64(length int) string {
	buf := make([]byte, length)
	if _, err := rand.Read(buf); err != nil {
		panic(err)
	}
	return base64.StdEncoding.EncodeToString(buf)
}

func randPassword(length int) string {
	const alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789-_"
	var out strings.Builder
	for out.Len() < length {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(alphabet))))
		if err != nil {
			panic(err)
		}
		out.WriteByte(alphabet[n.Int64()])
	}
	return out.String()
}

func (c *doClient) request(ctx context.Context, method string, path string, body any, out any) error {
	var reader io.Reader
	if body != nil {
		raw, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reader = bytes.NewReader(raw)
	}
	req, err := http.NewRequestWithContext(ctx, method, doAPIBase+path, reader)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		var payload struct {
			Message string `json:"message"`
			ID      string `json:"id"`
		}
		_ = json.Unmarshal(raw, &payload)
		message := strings.TrimSpace(payload.Message)
		if message == "" {
			message = strings.TrimSpace(payload.ID)
		}
		if message == "" {
			message = string(raw)
		}
		return fmt.Errorf("DigitalOcean API error (%d): %s", resp.StatusCode, message)
	}
	if out == nil || len(raw) == 0 {
		return nil
	}
	return json.Unmarshal(raw, out)
}

func (c *doClient) validateToken(ctx context.Context) error {
	return c.request(ctx, http.MethodGet, "/account", nil, &struct{}{})
}

func createDroplet(ctx context.Context, client *doClient, data input, userData string) (int, string, error) {
	name := makeDropletName()
	payload := map[string]any{
		"name":       name,
		"region":     data.region,
		"size":       data.size,
		"image":      dropletImage,
		"user_data":  userData,
		"backups":    false,
		"ipv6":       true,
		"monitoring": true,
		"tags":       []string{appName, "one-click"},
	}
	var response struct {
		Droplet struct {
			ID int `json:"id"`
		} `json:"droplet"`
	}
	if err := client.request(ctx, http.MethodPost, "/droplets", payload, &response); err != nil {
		return 0, "", err
	}
	if response.Droplet.ID == 0 {
		return 0, "", errors.New("DigitalOcean did not return a Droplet id")
	}
	return response.Droplet.ID, name, nil
}

func waitForDropletIP(ctx context.Context, client *doClient, dropletID int, ui *ui) (string, error) {
	started := time.Now()
	timeout := 10 * time.Minute
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	attempt := 0
	lastStatus := ""
	for {
		attempt++
		var response struct {
			Droplet struct {
				Status   string `json:"status"`
				Networks struct {
					V4 []struct {
						IPAddress string `json:"ip_address"`
						Type      string `json:"type"`
					} `json:"v4"`
				} `json:"networks"`
			} `json:"droplet"`
		}
		if err := client.request(ctx, http.MethodGet, fmt.Sprintf("/droplets/%d", dropletID), nil, &response); err != nil {
			return "", err
		}
		ip := ""
		for _, network := range response.Droplet.Networks.V4 {
			if network.Type == "public" && network.IPAddress != "" {
				ip = network.IPAddress
				break
			}
		}
		if response.Droplet.Status == "active" && ip != "" {
			ui.progressDone("Droplet provisioning", timeout, "status=active | public IPv4="+ip)
			return ip, nil
		}
		if attempt == 1 || attempt%2 == 0 || response.Droplet.Status != lastStatus {
			details := "status=" + fallback(response.Droplet.Status, "new")
			if ip == "" {
				details += " | public IPv4 pending"
			} else {
				details += " | assigned IPv4=" + ip + " | waiting for active"
			}
			ui.progressWait("Droplet provisioning", time.Since(started), timeout, details)
		}
		lastStatus = response.Droplet.Status
		if time.Since(started) > timeout {
			return "", errors.New("timed out waiting for the Droplet to become active and receive a public IP")
		}
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-ticker.C:
		}
	}
}

func createFirewall(ctx context.Context, client *doClient, dropletID int, dropletName string) (string, error) {
	anyAddresses := []string{"0.0.0.0/0", "::/0"}
	payload := map[string]any{
		"name":        dropletName + "-firewall",
		"droplet_ids": []int{dropletID},
		"inbound_rules": []map[string]any{
			{"protocol": "tcp", "ports": "22", "sources": map[string]any{"addresses": anyAddresses}},
			{"protocol": "tcp", "ports": "80", "sources": map[string]any{"addresses": anyAddresses}},
			{"protocol": "tcp", "ports": "443", "sources": map[string]any{"addresses": anyAddresses}},
		},
		"outbound_rules": []map[string]any{
			{"protocol": "tcp", "ports": "all", "destinations": map[string]any{"addresses": anyAddresses}},
			{"protocol": "udp", "ports": "all", "destinations": map[string]any{"addresses": anyAddresses}},
			{"protocol": "icmp", "destinations": map[string]any{"addresses": anyAddresses}},
		},
	}
	var response struct {
		Firewall struct {
			ID string `json:"id"`
		} `json:"firewall"`
	}
	if err := client.request(ctx, http.MethodPost, "/firewalls", payload, &response); err != nil {
		return "", err
	}
	if response.Firewall.ID == "" {
		return "", errors.New("DigitalOcean did not return a firewall id")
	}
	return response.Firewall.ID, nil
}

func deleteFirewall(ctx context.Context, client *doClient, firewallID string) error {
	if firewallID == "" {
		return nil
	}
	return client.request(ctx, http.MethodDelete, "/firewalls/"+firewallID, nil, nil)
}

func deleteDroplet(ctx context.Context, client *doClient, dropletID int) error {
	if dropletID == 0 {
		return errors.New("state file is missing Droplet id")
	}
	return client.request(ctx, http.MethodDelete, fmt.Sprintf("/droplets/%d", dropletID), nil, nil)
}

func waitForSSHPort(ctx context.Context, ip string, ui *ui) bool {
	started := time.Now()
	timeout := 5 * time.Minute
	last := "connection pending"
	for {
		conn, err := net.DialTimeout("tcp", net.JoinHostPort(ip, "22"), 5*time.Second)
		if err == nil {
			_ = conn.Close()
			ui.progressDone("SSH availability", timeout, "port=22 | ready")
			return true
		}
		last = err.Error()
		ui.progressWait("SSH availability", time.Since(started), timeout, "port=22 | last="+last)
		if time.Since(started) > timeout {
			return false
		}
		select {
		case <-ctx.Done():
			return false
		case <-time.After(10 * time.Second):
		}
	}
}

func waitForPublicHealth(ctx context.Context, publicURL string, ui *ui, timeout time.Duration) (healthResult, error) {
	target := publicURL + "/api/health"
	client := &http.Client{Timeout: 10 * time.Second, Transport: &http.Transport{TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12}}}
	started := time.Now()
	attempt := 0
	last := "waiting for first successful health check"
	for time.Since(started) < timeout {
		attempt++
		req, _ := http.NewRequestWithContext(ctx, http.MethodGet, target, nil)
		resp, err := client.Do(req)
		if err == nil {
			_ = resp.Body.Close()
			if resp.StatusCode == http.StatusOK {
				ui.progressDone("Public health check", timeout, fmt.Sprintf("attempt=%d | last=HTTP 200 | remaining=0s", attempt))
				return healthResult{Ready: true, ElapsedSeconds: int(time.Since(started).Seconds()), LastStatus: "HTTP 200"}, nil
			}
			last = fmt.Sprintf("HTTP %d", resp.StatusCode)
		} else {
			last = err.Error()
			var urlErr *url.Error
			if errors.As(err, &urlErr) {
				last = urlErr.Err.Error()
			}
		}
		remaining := maxDuration(0, timeout-time.Since(started))
		ui.progressWait("Public health check", time.Since(started), timeout, fmt.Sprintf("attempt=%d | last=%s | remaining=%s", attempt, last, formatDuration(remaining)))
		select {
		case <-ctx.Done():
			return healthResult{Ready: false, ElapsedSeconds: int(time.Since(started).Seconds()), LastStatus: last}, ctx.Err()
		case <-time.After(15 * time.Second):
		}
	}
	return healthResult{Ready: false, ElapsedSeconds: int(time.Since(started).Seconds()), LastStatus: last}, fmt.Errorf("timed out waiting for public health check. Last status: %s", last)
}

func runUpdate(ctx context.Context, ui *ui, args cliArgs) int {
	state, statePath, err := stateForUpdate(args)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	token, err := collectDOToken(args.token)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}

	webImage := appImageForVersion(args.version)
	workspaceImage := workspaceImageForVersion(args.version)
	ui.panel("Update plan", [][2]string{
		{"State file", statePath},
		{"Server IP", state.Deployment.IPAddress},
		{"App URL", state.Deployment.PublicURL},
		{"From version", fallback(state.Version, "unknown")},
		{"To version", args.version},
		{"Web image", webImage},
		{"Workspace image", workspaceImage},
	}, "info")

	client := &doClient{token: token, http: &http.Client{Timeout: 30 * time.Second}}
	started := ui.stage("Validating DigitalOcean API token")
	if err := client.validateToken(ctx); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("DigitalOcean API token accepted", started)

	started = ui.stage("Updating remote Compose configuration")
	script := renderUpdateScript(args.version, renderCompose())
	if err := runRemoteScript(ctx, ui, state.Deployment.IPAddress, state.Secrets.RootPassword, script); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("Remote stack updated to "+args.version, started)

	state.Version = args.version
	state.AppImage = webImage
	state.WorkspaceImage = workspaceImage
	state.UpdatedAt = time.Now().UTC().Format(time.RFC3339)
	writePath := statePath
	if writePath == "manual flags" {
		writePath, err = defaultStatePath()
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error:", err)
			return 1
		}
		state.Deployment.JSONFile = writePath
	}
	if err := writeStateFiles(state, writePath); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}

	if args.skipHealthWait {
		ui.warn("Skipping public health wait by request.")
		printSummary(ui, state.Deployment, nil)
		return 0
	}

	started = ui.stage("Waiting for updated public health check")
	health, err := waitForPublicHealth(ctx, state.Deployment.PublicURL, ui, defaultHealthWait)
	if err != nil {
		ui.warn(err.Error(), started)
	} else if health.Ready {
		ui.ok("Updated version answered the public health check", started)
	}
	printSummary(ui, state.Deployment, &health)
	return 0
}

func stateForUpdate(args cliArgs) (deploymentState, string, error) {
	if args.ipAddress != "" || args.sshPassword != "" {
		if args.ipAddress == "" || args.sshPassword == "" {
			return deploymentState{}, "", errors.New("--ip and --ssh-password must be provided together")
		}
		publicURL := strings.TrimSpace(args.publicURL)
		if publicURL == "" {
			publicURL = "https://" + buildDomainFromIP(args.ipAddress)
		}
		return deploymentState{
			AppName:        appName,
			Version:        defaultVersion,
			AppImage:       appImageForVersion(defaultVersion),
			WorkspaceImage: workspaceImageForVersion(defaultVersion),
			DBName:         dbName,
			Deployment: artifacts{
				IPAddress: args.ipAddress,
				Domain:    strings.TrimPrefix(strings.TrimPrefix(publicURL, "https://"), "http://"),
				PublicURL: publicURL,
			},
			Secrets: stateSecrets{RootPassword: args.sshPassword},
		}, "manual flags", nil
	}
	return readState(args.statePath)
}

func runDestroy(ctx context.Context, ui *ui, args cliArgs) int {
	state, statePath, err := stateForDestroy(args)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}

	token, err := collectDOToken(args.token)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}

	ui.panel("Destroy plan", [][2]string{
		{"State file", statePath},
		{"Droplet", fmt.Sprintf("%s (%d)", state.Deployment.DropletName, state.Deployment.DropletID)},
		{"Firewall", fallback(state.Deployment.FirewallID, "-")},
		{"Server IP", state.Deployment.IPAddress},
		{"App URL", state.Deployment.PublicURL},
	}, "warn")

	if !args.yes {
		reader := bufio.NewReader(os.Stdin)
		fmt.Print("Type DESTROY to permanently delete this Droplet: ")
		answer, err := reader.ReadString('\n')
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error:", err)
			return 1
		}
		if strings.TrimSpace(answer) != "DESTROY" {
			fmt.Fprintln(os.Stderr, "Error: destroy cancelled")
			return 1
		}
	}

	client := &doClient{token: token, http: &http.Client{Timeout: 30 * time.Second}}
	started := ui.stage("Validating DigitalOcean API token")
	if err := client.validateToken(ctx); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("DigitalOcean API token accepted", started)

	if state.Deployment.FirewallID != "" {
		started = ui.stage("Deleting firewall")
		if err := deleteFirewall(ctx, client, state.Deployment.FirewallID); err != nil {
			ui.warn("Firewall delete returned: "+err.Error(), started)
		} else {
			ui.ok("Deleted firewall "+state.Deployment.FirewallID, started)
		}
	}

	started = ui.stage("Deleting Droplet")
	if err := deleteDroplet(ctx, client, state.Deployment.DropletID); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return 1
	}
	ui.ok("Deleted Droplet "+state.Deployment.DropletName, started)
	ui.warn("Local credential/state files were left in place. Remove them manually if you no longer need recovery records.")
	return 0
}

func stateForDestroy(args cliArgs) (deploymentState, string, error) {
	if args.dropletID != 0 {
		return deploymentState{
			AppName: appName,
			Deployment: artifacts{
				DropletID:   args.dropletID,
				FirewallID:  args.firewallID,
				DropletName: fmt.Sprintf("%s-%d", appName, args.dropletID),
			},
		}, "manual flags", nil
	}
	return readState(args.statePath)
}

func renderUpdateScript(version, compose string) string {
	return fmt.Sprintf(`set -euo pipefail
timestamp() { date -u +"%%Y-%%m-%%dT%%H:%%M:%%SZ"; }
log() { printf '[update][%%s] %%s\n' "$(timestamp)" "$1"; }
set_env() {
  key="$1"
  value="$2"
  tmp="$(mktemp)"
  grep -v "^${key}=" /opt/%s/.env > "$tmp" || true
  printf '%%s=%%s\n' "$key" "$value" >> "$tmp"
  cat "$tmp" > /opt/%s/.env
  rm -f "$tmp"
}
cd /opt/%s
log 'Backing up current Compose and env files'
cp docker-compose.yml "docker-compose.yml.bak.$(date -u +%%Y%%m%%d-%%H%%M%%S)"
cp .env ".env.bak.$(date -u +%%Y%%m%%d-%%H%%M%%S)"
log 'Writing updated docker-compose.yml'
printf %%s %s | base64 -d > docker-compose.yml
log 'Writing versioned image settings'
set_env ARCHE_VERSION %s
set_env ARCHE_RELEASE_VERSION %s
set_env ARCHE_WEB_IMAGE %s
set_env OPENCODE_IMAGE %s
set -a
. /opt/%s/.env
set +a
log "Pulling ${ARCHE_WEB_IMAGE}"
docker pull "${ARCHE_WEB_IMAGE}"
log "Pulling ${OPENCODE_IMAGE}"
docker pull "${OPENCODE_IMAGE}"
log 'Recreating web service'
docker compose up -d web
docker compose ps
log 'Update complete'
`, appName, appName, appName, shellQuote(b64(compose)), shellQuote(version), shellQuote(version), shellQuote(appImageForVersion(version)), shellQuote(workspaceImageForVersion(version)), appName)
}

func runRemoteScript(ctx context.Context, ui *ui, ip, password, script string) error {
	sshPath := findSSH()
	if sshPath == "" {
		return errors.New("local ssh client not found")
	}
	askpassPath, err := createAskpassScript()
	if err != nil {
		return err
	}
	defer os.Remove(askpassPath)

	cmd := exec.CommandContext(ctx, sshPath,
		"-o", "StrictHostKeyChecking=no",
		"-o", "UserKnownHostsFile=/dev/null",
		"-o", "LogLevel=ERROR",
		"-o", "PreferredAuthentications=password",
		"-o", "PubkeyAuthentication=no",
		"-o", "KbdInteractiveAuthentication=no",
		"-o", "PasswordAuthentication=yes",
		"-o", "NumberOfPasswordPrompts=1",
		"-o", "ConnectTimeout=15",
		"root@"+ip,
		"bash -se",
	)
	cmd.Stdin = strings.NewReader(script)
	cmd.Env = append(os.Environ(),
		"DISPLAY=archectl",
		"SSH_ASKPASS="+askpassPath,
		"SSH_ASKPASS_REQUIRE=force",
		"ARCHE_SSH_PASSWORD="+password,
	)
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return err
	}

	progressDone := make(chan struct{})
	if !ui.verbose {
		started := time.Now()
		go func() {
			ticker := time.NewTicker(2 * time.Second)
			defer ticker.Stop()
			for {
				select {
				case <-progressDone:
					return
				case <-ticker.C:
					ui.progressWait("Remote update", time.Since(started), 10*time.Minute, "pulling images and restarting web")
				}
			}
		}()
	}

	var wg sync.WaitGroup
	scan := func(r io.Reader) {
		defer wg.Done()
		scanner := bufio.NewScanner(r)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line != "" {
				ui.remote(line)
			}
		}
	}
	wg.Add(2)
	go scan(stdout)
	go scan(stderr)
	err = cmd.Wait()
	wg.Wait()
	close(progressDone)
	if err == nil && !ui.verbose {
		ui.progressDone("Remote update", 10*time.Minute, "web restarted")
	}
	return err
}

type remoteStreamer struct {
	ui          *ui
	ip          string
	password    string
	sshPath     string
	cancel      context.CancelFunc
	attached    chan struct{}
	done        chan struct{}
	mu          sync.Mutex
	complete    bool
	lastError   string
	askpassPath string
}

func newRemoteStreamer(ui *ui, ip, password string) *remoteStreamer {
	return &remoteStreamer{ui: ui, ip: ip, password: password, sshPath: findSSH(), attached: make(chan struct{}), done: make(chan struct{})}
}

func (s *remoteStreamer) available() bool {
	return s.sshPath != ""
}

func (s *remoteStreamer) bootComplete() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.complete
}

func (s *remoteStreamer) start(parent context.Context) error {
	if s.sshPath == "" {
		return errors.New("ssh not found")
	}
	ctx, cancel := context.WithCancel(parent)
	s.cancel = cancel
	path, err := createAskpassScript()
	if err != nil {
		return err
	}
	s.askpassPath = path
	go s.run(ctx)
	return nil
}

func (s *remoteStreamer) waitUntilAttached(timeout time.Duration) bool {
	select {
	case <-s.attached:
		return true
	case <-time.After(timeout):
		return false
	}
}

func (s *remoteStreamer) stop() {
	if s.cancel != nil {
		s.cancel()
	}
	select {
	case <-s.done:
	case <-time.After(5 * time.Second):
	}
	if s.askpassPath != "" {
		_ = os.Remove(s.askpassPath)
	}
}

func (s *remoteStreamer) run(ctx context.Context) {
	defer close(s.done)
	defer func() {
		if s.askpassPath != "" {
			_ = os.Remove(s.askpassPath)
		}
	}()
	attachedClosed := false
	for ctx.Err() == nil {
		cmd := exec.CommandContext(ctx, s.sshPath,
			"-o", "StrictHostKeyChecking=no",
			"-o", "UserKnownHostsFile=/dev/null",
			"-o", "LogLevel=ERROR",
			"-o", "PreferredAuthentications=password",
			"-o", "PubkeyAuthentication=no",
			"-o", "KbdInteractiveAuthentication=no",
			"-o", "PasswordAuthentication=yes",
			"-o", "NumberOfPasswordPrompts=1",
			"-o", "ConnectTimeout=10",
			"root@"+s.ip,
			fmt.Sprintf("sh -lc 'touch /var/log/%s-bootstrap.log && tail -n +1 -F /var/log/%s-bootstrap.log'", appName, appName),
		)
		cmd.Stdin = nil
		cmd.Stderr = nil
		cmd.Env = append(os.Environ(),
			"DISPLAY=arche-installer",
			"SSH_ASKPASS="+s.askpassPath,
			"SSH_ASKPASS_REQUIRE=force",
			"ARCHE_SSH_PASSWORD="+s.password,
		)
		cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
		stdout, err := cmd.StdoutPipe()
		if err != nil {
			s.setError(err.Error())
			return
		}
		if err := cmd.Start(); err != nil {
			s.setError(err.Error())
			return
		}
		if !attachedClosed {
			close(s.attached)
			attachedClosed = true
		}
		scanner := bufio.NewScanner(stdout)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" {
				continue
			}
			s.ui.remote(line)
			if strings.Contains(line, "Bootstrap complete") {
				s.mu.Lock()
				s.complete = true
				s.mu.Unlock()
			}
		}
		err = cmd.Wait()
		if ctx.Err() != nil || s.bootComplete() {
			return
		}
		if err != nil {
			s.setError(err.Error())
		}
		s.ui.wait("Remote bootstrap log stream dropped. Retrying in 5s.")
		select {
		case <-ctx.Done():
			return
		case <-time.After(5 * time.Second):
		}
	}
}

func (s *remoteStreamer) setError(message string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.lastError = message
}

func createAskpassScript() (string, error) {
	file, err := os.CreateTemp("", "arche-askpass-*.sh")
	if err != nil {
		return "", err
	}
	path := file.Name()
	if _, err := file.WriteString("#!/bin/sh\nprintf '%s\\n' \"$ARCHE_SSH_PASSWORD\"\n"); err != nil {
		_ = file.Close()
		return "", err
	}
	if err := file.Close(); err != nil {
		return "", err
	}
	if err := os.Chmod(path, 0o700); err != nil {
		return "", err
	}
	return path, nil
}

func findSSH() string {
	path, err := exec.LookPath("ssh")
	if err != nil {
		return ""
	}
	return path
}

func renderEnvTemplate(data input, secret secretsData) string {
	return strings.TrimSpace(fmt.Sprintf(`
ACME_EMAIL=%s
ARCHE_DOMAIN=%s
ARCHE_PUBLIC_BASE_URL=%s
ARCHE_VERSION=%s
ARCHE_RELEASE_VERSION=%s
ARCHE_WEB_IMAGE=%s

DATABASE_URL=postgresql://postgres:%s@postgres:5432/%s?schema=public
POSTGRES_PASSWORD=%s

ARCHE_SESSION_PEPPER=%s
ARCHE_ENCRYPTION_KEY=%s
ARCHE_INTERNAL_TOKEN=%s
ARCHE_CONNECTOR_OAUTH_STATE_SECRET=%s
ARCHE_GATEWAY_TOKEN_SECRET=%s

ARCHE_COOKIE_SECURE=true
ARCHE_SESSION_TTL_DAYS=7

ARCHE_SEED_ADMIN_EMAIL=%s
ARCHE_SEED_ADMIN_PASSWORD=%s
ARCHE_SEED_ADMIN_SLUG=admin

CONTAINER_PROXY_HOST=docker-socket-proxy
CONTAINER_PROXY_PORT=2375
OPENCODE_IMAGE=%s
OPENCODE_NETWORK=arche-internal

KB_CONTENT_HOST_PATH=/opt/arche/kb-content
KB_CONFIG_HOST_PATH=/opt/arche/kb-config
ARCHE_USERS_PATH=/opt/arche/users
`, data.email, envPlaceholderDomain, envPlaceholderPublicBaseURL, data.version, data.version, appImageForVersion(data.version), secret.postgresPassword, dbName, secret.postgresPassword, secret.sessionPepper, secret.encryptionKey, secret.internalToken, secret.connectorOAuthStateSecret, secret.gatewayTokenSecret, data.email, secret.adminPassword, workspaceImageForVersion(data.version))) + "\n"
}

func renderCompose() string {
	return strings.TrimSpace(fmt.Sprintf(`
name: %s

services:
  traefik:
    image: docker.io/traefik:v3.6.7
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-socket-proxy:2375
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --api.dashboard=false
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_letsencrypt:/letsencrypt
    networks:
      - default
      - arche-internal
    depends_on:
      docker-socket-proxy:
        condition: service_healthy

  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      IMAGES: 1
      INFO: 1
      POST: 1
      VOLUMES: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - arche-internal
    healthcheck:
      test: ["CMD-SHELL", "test -S /var/run/docker.sock"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: docker.io/postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: %s
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - arche_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: "${ARCHE_WEB_IMAGE}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - arche-internal
    volumes:
      - /opt/arche/users:/opt/arche/users
      - /opt/arche/kb-content:/kb-content
      - /opt/arche/kb-config:/kb-config
    labels:
      - traefik.enable=true
      - traefik.docker.network=arche-internal
      - traefik.http.routers.arche.rule=Host("${ARCHE_DOMAIN}")
      - traefik.http.routers.arche.entrypoints=websecure
      - traefik.http.routers.arche.service=arche-web
      - traefik.http.routers.arche.tls=true
      - traefik.http.routers.arche.tls.certresolver=letsencrypt
      - traefik.http.services.arche-web.loadbalancer.server.port=%d

networks:
  default:
  arche-internal:
    name: arche-internal

volumes:
  arche_postgres:
  traefik_letsencrypt:
`, appName, dbName, appPort)) + "\n"
}

func renderBootstrapScript() string {
	template := `
#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
STEP_NO=0

timestamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log() { printf '[bootstrap][%s] %s\n' "$(timestamp)" "$1"; }
step() { STEP_NO=$((STEP_NO + 1)); printf '\n[bootstrap][%s] STEP %02d %s\n' "$(timestamp)" "$STEP_NO" "$1"; }
fail() { printf '[bootstrap][%s] ERROR exit=%s line=%s command=%s\n' "$(timestamp)" "$1" "$2" "$3"; exit "$1"; }
trap 'fail "$?" "$LINENO" "$BASH_COMMAND"' ERR

metadata_ip() { curl -fsS http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address; }
ensure_bare_repo() {
  local repo="$1"
  if git --git-dir="$repo" rev-parse --is-bare-repository >/dev/null 2>&1; then return; fi
  mkdir -p "$(dirname "$repo")"
  rm -rf "$repo"
  git init --bare --initial-branch=main "$repo" >/dev/null 2>&1 || git init --bare "$repo" >/dev/null 2>&1
  git --git-dir="$repo" symbolic-ref HEAD refs/heads/main >/dev/null 2>&1 || true
}

step 'Configuring SSH access'
sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd || systemctl restart ssh
log 'Root login and password authentication are enabled for first access'

step 'Installing system packages'
apt-get update -y
apt-get install -y ca-certificates curl git
log 'Installed ca-certificates, curl, and git'

step 'Installing Docker'
curl -fsSL https://get.docker.com | sh
systemctl enable --now docker
log "$(docker --version)"
log "$(docker compose version)"

step 'Deriving public endpoint'
PUBLIC_IP="$(metadata_ip)"
ARCHE_DOMAIN="{{APP_NAME}}-${PUBLIC_IP//./-}.nip.io"
ARCHE_PUBLIC_BASE_URL="https://${ARCHE_DOMAIN}"
log "Detected public IP ${PUBLIC_IP}"
log "Derived public domain ${ARCHE_DOMAIN}"
log "Using public URL ${ARCHE_PUBLIC_BASE_URL}"

step 'Preparing persistent directories and repositories'
mkdir -p /opt/{{APP_NAME}} /opt/{{APP_NAME}}/users /opt/{{APP_NAME}}/kb-content /opt/{{APP_NAME}}/kb-config
ensure_bare_repo /opt/{{APP_NAME}}/kb-content
ensure_bare_repo /opt/{{APP_NAME}}/kb-config
log 'Ensured /opt/arche/users, /opt/arche/kb-content, and /opt/arche/kb-config exist'

step 'Rendering runtime configuration'
cp /opt/{{APP_NAME}}/.env.template /opt/{{APP_NAME}}/.env
sed -i "s|{{ENV_PLACEHOLDER_DOMAIN}}|${ARCHE_DOMAIN}|g" /opt/{{APP_NAME}}/.env
sed -i "s|{{ENV_PLACEHOLDER_PUBLIC_URL}}|${ARCHE_PUBLIC_BASE_URL}|g" /opt/{{APP_NAME}}/.env
log 'Wrote /opt/arche/.env and injected the live public URL'

step 'Pulling container images'
set -a
. /opt/{{APP_NAME}}/.env
set +a
log "Pulling web image ${ARCHE_WEB_IMAGE}"
docker pull "${ARCHE_WEB_IMAGE}"
log "Pulling workspace image ${OPENCODE_IMAGE}"
docker pull "${OPENCODE_IMAGE}"

step 'Starting Arche stack'
cd /opt/{{APP_NAME}}
docker compose up -d
docker compose ps
log 'Compose stack started'

step 'Recording bootstrap summary'
cat > /opt/{{APP_NAME}}/bootstrap-summary.txt <<EOF
public_ip=${PUBLIC_IP}
domain=${ARCHE_DOMAIN}
public_url=${ARCHE_PUBLIC_BASE_URL}
compose_dir=/opt/{{APP_NAME}}
EOF

log 'Bootstrap complete. If the public URL is not ready yet, keep tailing /var/log/arche-bootstrap.log and docker compose logs.'
`
	replacer := strings.NewReplacer(
		"{{APP_NAME}}", appName,
		"{{ENV_PLACEHOLDER_DOMAIN}}", envPlaceholderDomain,
		"{{ENV_PLACEHOLDER_PUBLIC_URL}}", envPlaceholderPublicBaseURL,
	)
	return strings.TrimSpace(replacer.Replace(template)) + "\n"
}

func renderCloudInit(secret secretsData, envTemplate, compose, bootstrap string) string {
	return strings.TrimSpace(fmt.Sprintf(`#cloud-config
disable_root: false
ssh_pwauth: true
chpasswd:
  expire: false
  list: |
    root:%s
write_files:
  - path: /opt/%s/.env.template
    owner: root:root
    permissions: "0600"
    encoding: b64
    content: %s
  - path: /opt/%s/docker-compose.yml
    owner: root:root
    permissions: "0644"
    encoding: b64
    content: %s
  - path: /opt/%s/bootstrap.sh
    owner: root:root
    permissions: "0700"
    encoding: b64
    content: %s
runcmd:
  - bash -lc '/opt/%s/bootstrap.sh > /var/log/%s-bootstrap.log 2>&1'
final_message: '%s bootstrap finished'
`, secret.rootPassword, appName, b64(envTemplate), appName, b64(compose), appName, b64(bootstrap), appName, appName, appName)) + "\n"
}

func validateTemplates(version string) error {
	sample := input{token: "sample", email: "admin@example.com", size: defaultDropletSize, region: defaultDropletRegion, version: version}
	secret := generateSecrets()
	envTemplate := renderEnvTemplate(sample, secret)
	compose := renderCompose()
	envKeys := map[string]bool{}
	for _, line := range strings.Split(envTemplate, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || !strings.Contains(line, "=") {
			continue
		}
		envKeys[strings.SplitN(line, "=", 2)[0]] = true
	}
	re := regexp.MustCompile(`\$\{([A-Z0-9_]+)(?::[^}]*)?\}`)
	missing := map[string]bool{}
	for _, match := range re.FindAllStringSubmatch(compose, -1) {
		if len(match) > 1 && !envKeys[match[1]] {
			missing[match[1]] = true
		}
	}
	if len(missing) > 0 {
		keys := make([]string, 0, len(missing))
		for key := range missing {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		return fmt.Errorf("docker-compose references env vars missing from .env: %s", strings.Join(keys, ", "))
	}
	if !strings.Contains(envTemplate, envPlaceholderDomain) || !strings.Contains(envTemplate, envPlaceholderPublicBaseURL) {
		return errors.New("dynamic domain placeholders are missing from generated .env template")
	}
	return nil
}

func allocateLocalPaths() (string, string, error) {
	dir, err := deploymentStateDir()
	if err != nil {
		return "", "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", "", err
	}
	stem := appName + "-" + time.Now().UTC().Format("20060102-150405")
	return filepath.Join(dir, stem+".txt"), filepath.Join(dir, stem+".json"), nil
}

func writeLocalFiles(data input, secret secretsData, result artifacts) error {
	text := fmt.Sprintf(`Arche one-click deployment
=========================

Droplet id:        %d
Firewall id:       %s
Droplet name:      %s
Region:            %s
Size:              %s
Public IP:         %s
Public domain:     %s
Public URL:        %s

SSH user:          root
SSH password:      %s
SSH command:       ssh root@%s

Version:           %s
App image:         %s
Workspace image:   %s
Admin email:       %s
Admin password:    %s
Admin slug:        admin

PostgreSQL db:     %s
PostgreSQL user:   postgres
PostgreSQL pass:   %s

ARCHE_SESSION_PEPPER=%s
ARCHE_ENCRYPTION_KEY=%s
ARCHE_INTERNAL_TOKEN=%s
ARCHE_GATEWAY_TOKEN_SECRET=%s
ARCHE_CONNECTOR_OAUTH_STATE_SECRET=%s

Useful commands:
ssh root@%s 'tail -f /var/log/%s-bootstrap.log'
ssh root@%s 'cd /opt/%s && docker compose logs -f web'
ssh root@%s 'cd /opt/%s && docker compose ps'
`, result.DropletID, result.FirewallID, result.DropletName, data.region, data.size, result.IPAddress, result.Domain, result.PublicURL, secret.rootPassword, result.IPAddress, data.version, appImageForVersion(data.version), workspaceImageForVersion(data.version), result.AdminEmail, secret.adminPassword, dbName, secret.postgresPassword, secret.sessionPepper, secret.encryptionKey, secret.internalToken, secret.gatewayTokenSecret, secret.connectorOAuthStateSecret, result.IPAddress, appName, result.IPAddress, appName, result.IPAddress, appName)
	if err := os.WriteFile(result.CredentialsFile, []byte(text), 0o600); err != nil {
		return err
	}
	state := deploymentState{
		AppName:        appName,
		Version:        data.version,
		AppImage:       appImageForVersion(data.version),
		WorkspaceImage: workspaceImageForVersion(data.version),
		DBName:         dbName,
		Input: stateInput{
			Email:         data.email,
			DropletSize:   data.size,
			DropletRegion: data.region,
		},
		Deployment: result,
		Secrets: stateSecrets{
			PostgresPassword:          secret.postgresPassword,
			SessionPepper:             secret.sessionPepper,
			EncryptionKey:             secret.encryptionKey,
			InternalToken:             secret.internalToken,
			GatewayTokenSecret:        secret.gatewayTokenSecret,
			ConnectorOAuthStateSecret: secret.connectorOAuthStateSecret,
			AdminPassword:             secret.adminPassword,
			RootPassword:              secret.rootPassword,
		},
		UpdatedAt: time.Now().UTC().Format(time.RFC3339),
	}
	return writeStateFiles(state, result.JSONFile)
}

func printSummary(ui *ui, result artifacts, health *healthResult) {
	status := "bootstrapping"
	tone := "warn"
	healthWait := "skipped"
	lastCheck := "-"
	if health != nil {
		healthWait = formatDuration(time.Duration(health.ElapsedSeconds) * time.Second)
		lastCheck = health.LastStatus
		if health.Ready {
			status = "ready"
			tone = "success"
		}
	}
	ui.print("")
	ui.panel("Deployment complete", [][2]string{
		{"Status", status},
		{"Server IP", result.IPAddress},
		{"App URL", result.PublicURL},
		{"Credentials", result.CredentialsFile},
		{"JSON record", result.JSONFile},
		{"Health wait", healthWait},
		{"Last check", lastCheck},
	}, tone)
	if health == nil || !health.Ready {
		ui.warn("The server may still be finishing first boot. Keep the bootstrap log open if the URL is not ready yet.")
	} else {
		ui.ok("Arche answered the public health check and is ready to open at: "+result.PublicURL, time.Time{})
	}
}

func makeDropletName() string {
	return appName + "-" + time.Now().UTC().Format("20060102-150405")
}

func appImageForVersion(version string) string {
	return appImageRepo + ":" + version
}

func workspaceImageForVersion(version string) string {
	return workspaceImageRepo + ":" + version
}

func inferVersion(image string) string {
	_, version, ok := strings.Cut(image, ":")
	if !ok || strings.TrimSpace(version) == "" {
		return defaultVersion
	}
	return version
}

func validateVersion(version string) error {
	if version == defaultVersion {
		return nil
	}
	matched, err := regexp.MatchString(`^v[0-9]+\.[0-9]+\.[0-9]+([-.+][A-Za-z0-9][A-Za-z0-9.-]*)?$`, version)
	if err != nil {
		return err
	}
	if !matched {
		return fmt.Errorf("version must be %q or a tag like v1.2.3", defaultVersion)
	}
	return nil
}

func buildDomainFromIP(ip string) string {
	return appName + "-" + strings.ReplaceAll(ip, ".", "-") + ".nip.io"
}

func deploymentStateDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".arche", "deployments"), nil
}

func defaultStatePath() (string, error) {
	dir, err := deploymentStateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "current.json"), nil
}

func resolveStatePath(path string) (string, error) {
	if strings.TrimSpace(path) != "" {
		return path, nil
	}
	return defaultStatePath()
}

func writeStateFiles(state deploymentState, timestampPath string) error {
	raw, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(timestampPath), 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(timestampPath, raw, 0o600); err != nil {
		return err
	}
	currentPath, err := defaultStatePath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(currentPath), 0o700); err != nil {
		return err
	}
	return os.WriteFile(currentPath, raw, 0o600)
}

func readState(path string) (deploymentState, string, error) {
	resolved, err := resolveStatePath(path)
	if err != nil {
		return deploymentState{}, "", err
	}
	raw, err := os.ReadFile(resolved)
	if err != nil {
		return deploymentState{}, "", fmt.Errorf("read state file %s: %w", resolved, err)
	}
	var state deploymentState
	if err := json.Unmarshal(raw, &state); err != nil {
		return deploymentState{}, "", fmt.Errorf("parse state file %s: %w", resolved, err)
	}
	if state.Deployment.IPAddress == "" {
		var legacy struct {
			AppName        string          `json:"app_name"`
			AppImage       string          `json:"app_image"`
			WorkspaceImage string          `json:"workspace_image"`
			DBName         string          `json:"db_name"`
			Input          stateInput      `json:"input"`
			Deployment     legacyArtifacts `json:"deployment"`
			Secrets        stateSecrets    `json:"secrets"`
		}
		if err := json.Unmarshal(raw, &legacy); err == nil && legacy.Deployment.IPAddress != "" {
			state = deploymentState{
				AppName:        fallback(legacy.AppName, appName),
				Version:        inferVersion(legacy.AppImage),
				AppImage:       fallback(legacy.AppImage, appImageForVersion(defaultVersion)),
				WorkspaceImage: fallback(legacy.WorkspaceImage, workspaceImageForVersion(defaultVersion)),
				DBName:         fallback(legacy.DBName, dbName),
				Input:          legacy.Input,
				Deployment: artifacts{
					DropletID:       legacy.Deployment.DropletID,
					FirewallID:      legacy.Deployment.FirewallID,
					DropletName:     legacy.Deployment.DropletName,
					IPAddress:       legacy.Deployment.IPAddress,
					Domain:          legacy.Deployment.Domain,
					PublicURL:       legacy.Deployment.PublicURL,
					AdminEmail:      legacy.Deployment.AdminEmail,
					CredentialsFile: legacy.Deployment.CredentialsFile,
					JSONFile:        legacy.Deployment.JSONFile,
				},
				Secrets:   legacy.Secrets,
				UpdatedAt: time.Now().UTC().Format(time.RFC3339),
			}
		}
	}
	if state.Deployment.IPAddress == "" || state.Secrets.RootPassword == "" {
		return deploymentState{}, "", fmt.Errorf("state file %s is missing SSH connection details", resolved)
	}
	return state, resolved, nil
}

func collectDOToken(flagValue string) (string, error) {
	token := strings.TrimSpace(flagValue)
	if token == "" {
		token = strings.TrimSpace(os.Getenv("DIGITALOCEAN_TOKEN"))
	}
	if token == "" {
		fmt.Print("DigitalOcean API token: ")
		raw, err := term.ReadPassword(int(os.Stdin.Fd()))
		fmt.Println()
		if err != nil {
			return "", fmt.Errorf("read DigitalOcean token: %w", err)
		}
		token = strings.TrimSpace(string(raw))
	}
	if token == "" {
		return "", errors.New("DigitalOcean API token is required")
	}
	return token, nil
}

func b64(value string) string {
	return base64.StdEncoding.EncodeToString([]byte(value))
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return strconv.Quote(value)
}

func fallback(value, defaultValue string) string {
	if value == "" {
		return defaultValue
	}
	return value
}

func withDuration(message string, started time.Time) string {
	if started.IsZero() {
		return message
	}
	return message + " (" + formatDuration(time.Since(started)) + ")"
}

func formatDuration(value time.Duration) string {
	if value < 0 {
		value = 0
	}
	total := int(value.Round(time.Second).Seconds())
	hours := total / 3600
	minutes := (total % 3600) / 60
	seconds := total % 60
	if hours > 0 {
		return fmt.Sprintf("%dh %dm %ds", hours, minutes, seconds)
	}
	if minutes > 0 {
		return fmt.Sprintf("%dm %ds", minutes, seconds)
	}
	return fmt.Sprintf("%ds", seconds)
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func maxDuration(a, b time.Duration) time.Duration {
	if a > b {
		return a
	}
	return b
}
