'use strict'

const DEFAULT_NEW_VAULT_NAME = 'my-vault'

const DESKTOP_DATABASE_FILE_NAME = '.arche.db'
const DESKTOP_KB_CONFIG_DIR_NAME = '.kb-config'
const DESKTOP_KB_CONTENT_DIR_NAME = '.kb-content'
const DESKTOP_MANIFEST_FILE_NAME = '.arche-vault.json'
const DESKTOP_OPENCODE_RUNTIME_DIR_NAME = 'opencode'
const DESKTOP_RUNTIME_DIR_NAME = '.runtime'
const DESKTOP_SECRETS_DIR_NAME = '.secrets'
const DESKTOP_USERS_DIR_NAME = '.users'
const DESKTOP_WORKSPACE_DIR_NAME = 'workspace'

const LOCAL_DESKTOP_USER_SLUG = 'local'

module.exports = {
  DEFAULT_NEW_VAULT_NAME,
  DESKTOP_DATABASE_FILE_NAME,
  DESKTOP_KB_CONFIG_DIR_NAME,
  DESKTOP_KB_CONTENT_DIR_NAME,
  DESKTOP_MANIFEST_FILE_NAME,
  DESKTOP_OPENCODE_RUNTIME_DIR_NAME,
  DESKTOP_RUNTIME_DIR_NAME,
  DESKTOP_SECRETS_DIR_NAME,
  DESKTOP_USERS_DIR_NAME,
  DESKTOP_WORKSPACE_DIR_NAME,
  LOCAL_DESKTOP_USER_SLUG,
}
